baseURL = "https://vikki.pages.dev"
title = "VSS"
theme = "glitch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Vikki's Personal Website for portfolio and blogs "
  copyright = "Copyright © 2023 Vikki"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/blog/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 10


  [[menu.main]]
    identifier = "contact"
    name = "contact"
    title = "contact"
    url = "/contact/"
    weight = 30


[[menu.main]]
    identifier = "socials"
    name = "socials"
    title = "socials"
    url = "https://socials-heyvikki.pages.dev/"
    weight = 40




[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
