
baseURL = "https://1in1b.github.io"
title = "1IN1B"
theme = "twenty-twenty-hugo"
languageName = "En"
languageCode = "en-us"
paginate = "6"
summaryLength = "10"
disableLanguages = [] 


############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "About"
URL = "about/"
weight = 2


[[menu.main]]
name = "Contact"
URL = "contact/"
weight = 4




#################### default parameters ################################
[params]
# Meta data
description = "This is 1IN1B, We Develop"
author = "1IN1B"

# favicon
[params.favicon]
favicon = "images/136827822.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# banner
[params.banner]
heading = "Hello Everyone, we are 1IN1B 👋"
image = "images/136827822.png"


# call to action
[params.call_to_action]
enable = true
title = "Contact us for more information."
content = "You can contact US using Mail, for more details you can visit the Contact page."
button_label = "Contact Us"
button_url = "contact/"

# gallery
[params.gallery]
enable = true




# footer
[params.footer]
title = "About 1IN1B"
content = " We build world class free and open-source software."
address = " Content licensed under CC-BY-SA 3.0, Bhopal, India"
hours = "Monday–Friday: 9:00AM–5:00PM <br> Saturday: 11:00AM–3:00PM"
copyright = "Copyright &copy; 1IN1B, Content licensed under CC-BY-SA 3.0."

############################# social site ########################
[params.social]
facebook = "https://Facebook.com"
twitter = "https://Twitter.com"
instagram = "https://instagram.com"
email = "mailto:singhvikal891@gmail.com"
